### ISSUE TITLE
toString() - Am I missing something

### ISSUE THREAD

**Issue by realchandan** [G00fY2/quickie#114]
Hi there!

When I do -

```kt
    @OptIn(ExperimentalStdlibApi::class)
    private val scanQrCodeLauncher = registerForActivityResult(ScanQRCode()) { result ->
        val actualQrRawValue =
            result.toString().removePrefix("QRSuccess(content=Plain(rawValue=")
                .removeSuffix("))");
    }
```

in the `result.toString()` I get `QRSuccess(content=Plain(rawValue=<ACTUAL_QR_CODE_VALUE>))` and then the actual qr code value, Is this expected behavior or am I missing something?

Is there a way to get the `ACTUAL_QR_CODE_VALUE` directly?

**Comment by G00fY2** [comment]
Take a look over here: https://github.com/G00fY2/quickie/issues/103#issuecomment-1516851392

You first have to make sure that your result is a successful response in order to get the rawValue. Do not use `.toString`.

**Comment by binbard** [comment]
Unresolved reference: rawValue ?
