### ISSUE TITLE
Barcode Scanning is not working on Devices Managed by MDM-Android

### ISSUE THREAD

**Issue by RAMESHKUMAR502** [G00fY2/quickie#117]
Barcode Scanning is not working on Devices Managed by MDM-Android

We have using MLKit for Bar code and QR code Scanning, But one of our Customer have disabled the Play services on their devices, and Barcode scanning is not working.

Is there any way we can support ML Kit Barcode on the devices where there are no Google Play services installed?

Can i get the code where if the Play services not supported how to use ML Kit

**Comment by G00fY2** [comment]
For me running the **unbundled** version of my library (which uses `com.google.mlkit:barcode-scanning` in contrast to `com.google.android.gms:play-services-mlkit-barcode-scanning` used by the bundled flavor) is working perfectly fine on an emulator without any Google Play nor Google APIs (pure AOSP system image).
