### ISSUE TITLE
Unable to read encrypted qr codes

### ISSUE THREAD

**Issue by sami667778** [G00fY2/quickie#118]
Unable to read encrypted qr codes
![sample2](https://github.com/G00fY2/quickie/assets/139883439/bb8bab8b-b72b-4fb8-adab-244909b93758)
Please add character set support.
Thanks

**Comment by G00fY2** [comment]
Hi,

the changes in #119 should allow you to handle all types of encodings. If the barcode is non-UTF-8 than you can use the `rawBytes` instead of `rawValue` in the next release.

This should resolve your request about encrypted QR codes, right?
