### ISSUE TITLE
Google code scanner buggy

### ISSUE THREAD

**Issue by bonnjalal** [G00fY2/quickie#137]
Google code scanner is very buggy so please don't recommend it, it will waste the developer's time.
https://issuetracker.google.com/issues/261579118

> Note: At Google I/O 2022 the [Google code scanner](https://developers.google.com/ml-kit/code-scanner) was announced. You should consider using it instead of quickie unbundled. If you want to support devices without Play Services or like to ship the latest ML Kit model - use quickie bundled.

**Comment by G00fY2** [comment]
After reading the comments in the linked Google issue I decided to remove the reference about Google code scanner from the README. Also it's still in beta nearly 2 years after release.
