### ISSUE TITLE
[Feature Request] Configure to Keep the Screen On

### ISSUE THREAD

**Issue by thproflord** [G00fY2/quickie#145]
Currently I need the screen to keep turned On when I'm in the scanner, the solution I have currently and is not my favorite is with a Wakelock,
Will be nice to configure a flag FLAG_KEEP_SCREEN_ON because flags only live in the activity that they are added, so from the activity where the scanners is called will not work with the scanner

**Comment by G00fY2** [comment]
Closed with #173
