### ISSUE TITLE
FOSS version

### ISSUE THREAD

**Issue by T8RIN** [G00fY2/quickie#178]
Could you add third flavor with zxing?

like this https://github.com/T8RIN/quickie-foss

**Comment by G00fY2** [comment]
Hi and thanks for reaching out!
This library is tightly coupled to ML Kit. Adding support for zxing would require fundamental changes. I am sorry if this library does not comply with your FOSS requirements. I think there are already a lot of zxing based libraries out there you could check out.

**Comment by T8RIN** [comment]
But my fork is implementing zxing, that was not so hard, i can try to add foss flavor and PR, but you can do it too

**Comment by T8RIN** [comment]
Thing i like, that using this approach both foss and non foss versions have same ui

**Comment by G00fY2** [comment]
I don't say that it is not possible, but it requires a lot of changes and adds complexity and additonal testing. I choose ML Kit over zxing because it's superior scanning capabilities.
If this library does not meet your FOSS requirements, feels free to create your own fork or use the code as a guidance to create this functionality as part of you app.

**Comment by T8RIN** [comment]
I know, I already did that🐸

**Comment by T8RIN** [comment]
I like mlkit too, but it can't be published on f-droid then, so i have separate versions

**Comment by G00fY2** [comment]
I am sorry that ML Kit does not comply with F-Droids FOSS requirements. But this is actually a known issue for all libraries that rely on ML Kit. The readme of `quickie` points out the usage of ML Kit in the first sentence.

**Comment by michaelWuensch** [comment]
@G00fY2 @T8RIN My app is on F-Droid and I'd like to upgrade my scanner library to quickie or a custom ML Kit implementation.
Aside from here I can nowhere find any hints that ML Kit cannot be used when publishing on F-Droid. Do you have any sources or links where this claim is confirmed?
Thanks for your help.

**Comment by T8RIN** [comment]
It cannot be used because mlkit is not foss library

**Comment by T8RIN** [comment]
This doesn't determine whether the library is foss or not, because mlkit is closed source - proprietary library with link to google services
