### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by NeeroMeero** [G00fY2/quickie#2]
I have some errors, when i run your examples:

Access denied finding property "vendor.camera.aux.packagelist"
Access denied finding property "vendor.camera.aux.packagelist"
Access denied finding property "persist.vendor.camera.privapp.list"
Access denied finding property "vendor.camera.hal1.packagelist"

I try fix this, but i realy dont understand how resolve this problem

used guide for fix:
https://stackoverflow.com/questions/55990262/access-denied-for-property-vendor-camera-aux-packagelist

**Comment by G00fY2** [comment]
Hi how did you run the examples? From the APKs in the github Releases or did you build the app yourself?

Which device are you testing on? I have not changed any logic regarding camera usage. This is all handled by CameraX. Please see if their sample app is working for you: https://github.com/android/camera-samples/tree/master/CameraXBasic

**Comment by G00fY2** [comment]
Closed due to no response.
