### ISSUE TITLE
Can i have my own custom design in place of QROverlayView

### ISSUE THREAD

**Issue by pradeep-orbi** [G00fY2/quickie#20]
Instead of showing a square box in scanning screen, i want to add my own custom design. Is it possible using this library ?
Anyways, you said because of the limitations of ML kit, now entire screen image is captured, not just the square box. Then why not allow us to have custom design for Scanning screen ?

**Comment by G00fY2** [comment]
Currently you can only change the icon and the wording of the QR overlay. Please see this comment to understand the idea behinde the limitations of this library: https://github.com/G00fY2/quickie/pull/14#issuecomment-877804346

I think it will be easy to add a custom overlay once https://github.com/G00fY2/quickie/issues/12 is available. Feel free to follow this issue or use this project as a starting point to implement a custom QR activity. :slightly_smiling_face:
