### ISSUE TITLE
Request removing `<uses-feature android:name="android.hardware.camera"/>`

### ISSUE THREAD

**Issue by kyze8439690** [G00fY2/quickie#44]
Add `<uses-feature android:name="android.hardware.camera"/>` in AndroidManifest.xml by default will cause app which integrated this library won't be able to be installed on devices without camera hardware. 

Sometime QRCode scanning function is not the core function of the app and camera hardware should not be required.

**Comment by kyze8439690** [comment]
I hope my app support running on ChromeOS devices which may have no camera, use code below solve my problem:

```xml
<uses-feature android:name="android.hardware.camera" android:required="false" tools:replace="required"/>
```

**Comment by G00fY2** [comment]
Hi @kyze8439690 and thanks for the feedback.

I agree with your suggestion. The camera hardware should not be mandatory. But removing this flag would not help. The docs state:
> [...] if an application requests the `CAMERA` permission but does not declare a `<uses-feature>` element for `android.hardware.camera`, Google Play considers that the application requires a camera and should not be shown to users whose devices do not offer a camera.

Therefore with ccda3a9 I set the feature to `required="false"`.

I will keep this ticket open until I released an update.
