### ISSUE TITLE
Single dimension barcode support

### ISSUE THREAD

**Issue by Endless-Lemniscate** [G00fY2/quickie#5]
Are you planning to add support for scanning conventional 1-D barcodes?
As far as i know ML-kit supports different types of codes. It would be great to have opportunity to choose code types in ScanQrCode class.
Thanks

**Comment by Endless-Lemniscate** [comment]
Great job, by the way. The most convenient and beautiful library for my taste

**Comment by G00fY2** [comment]
Hi @Endless-Lemniscate,

yes you are right, ML Kit offers a lot more formats: [Barcode.BarcodeFormat](https://developers.google.com/android/reference/com/google/mlkit/vision/barcode/Barcode.BarcodeFormat)

Currently the format is limited to QR codes (thats where the name comes from 😄):
https://github.com/G00fY2/quickie/blob/183cd14c48d358cc3073de6e9aeea75e13f2ecd3/quickie/src/main/kotlin/com/g00fy2/quickie/QRCodeAnalyzer.kt#L18

I'm planing to add some sort of configuration or different launch modes to the library. One reason I'm currently hesitating, is that I'd like to have proper replacement for the icon and wording inside of the scanning overlay. Maybe I'll add a configurable mode where the caller has to define the icon drawable and text resource.

Will update this issue once I find some time to add this feature.

**Comment by G00fY2** [comment]
You are now able to configure the supported BarcodeFormats with [release 1.1.0](https://github.com/G00fY2/quickie/releases/tag/1.1.0)

**Comment by Endless-Lemniscate** [comment]
Thank you so much!
