### ISSUE TITLE
[Feature Request] Configurable torch toggle

### ISSUE THREAD

**Issue by atrashler** [G00fY2/quickie#7]
Have integrated your library in my project (https://play.google.com/store/apps/details?id=com.wb.clipboard.pro), version 6.x.

The configurable torch toggle can be a very handy addition when scanning in the dark.

Anyway your library is very useful:-)

Thanks!

**Comment by G00fY2** [comment]
@atrashler this feature is available with [1.2.0-rc01](https://github.com/G00fY2/quickie/releases/tag/1.2.0-rc01). Feel free to check it out and leave some feedback.
